[package]
name = "actix_api"
version = "0.1.0"
authors = ["Jon Gucciardi <jon.gucciardi@catapultsystems.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
